//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MeshPublisher
{
    [Serializable]
    public class CustomMeshMsg : Message
    {
        public const string k_RosMessageName = "mesh_publisher/CustomMesh";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg[] vertices;
        public double x;
        public double y;
        public double z;
        public uint[] triangles;
        public Std.ColorRGBAMsg[] vertex_colors;
        public float r;
        public float g;
        public float b;
        public float a;

        public CustomMeshMsg()
        {
            this.vertices = new Geometry.PointMsg[0];
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.triangles = new uint[0];
            this.vertex_colors = new Std.ColorRGBAMsg[0];
            this.r = 0.0f;
            this.g = 0.0f;
            this.b = 0.0f;
            this.a = 0.0f;
        }

        public CustomMeshMsg(Geometry.PointMsg[] vertices, double x, double y, double z, uint[] triangles, Std.ColorRGBAMsg[] vertex_colors, float r, float g, float b, float a)
        {
            this.vertices = vertices;
            this.x = x;
            this.y = y;
            this.z = z;
            this.triangles = triangles;
            this.vertex_colors = vertex_colors;
            this.r = r;
            this.g = g;
            this.b = b;
            this.a = a;
        }

        public static CustomMeshMsg Deserialize(MessageDeserializer deserializer) => new CustomMeshMsg(deserializer);

        private CustomMeshMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vertices, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.triangles, sizeof(uint), deserializer.ReadLength());
            deserializer.Read(out this.vertex_colors, Std.ColorRGBAMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.r);
            deserializer.Read(out this.g);
            deserializer.Read(out this.b);
            deserializer.Read(out this.a);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.vertices);
            serializer.Write(this.vertices);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.WriteLength(this.triangles);
            serializer.Write(this.triangles);
            serializer.WriteLength(this.vertex_colors);
            serializer.Write(this.vertex_colors);
            serializer.Write(this.r);
            serializer.Write(this.g);
            serializer.Write(this.b);
            serializer.Write(this.a);
        }

        public override string ToString()
        {
            return "CustomMeshMsg: " +
            "\nvertices: " + System.String.Join(", ", vertices.ToList()) +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\ntriangles: " + System.String.Join(", ", triangles.ToList()) +
            "\nvertex_colors: " + System.String.Join(", ", vertex_colors.ToList()) +
            "\nr: " + r.ToString() +
            "\ng: " + g.ToString() +
            "\nb: " + b.ToString() +
            "\na: " + a.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
